"""Add program_id to AdvisorAssignment

Revision ID: a36a13238e05
Revises: 3f12e20d07d6
Create Date: 2025-03-10 21:20:12.491661

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a36a13238e05'
down_revision = '3f12e20d07d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('advisor_assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('program_id', sa.String(length=36), nullable=False))
        batch_op.create_foreign_key(None, 'programs', ['program_id'], ['id'])

    with op.batch_alter_table('programs', schema=None) as batch_op:
        batch_op.alter_column('available_scholarships',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Boolean(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('programs', schema=None) as batch_op:
        batch_op.alter_column('available_scholarships',
               existing_type=sa.Boolean(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)

    with op.batch_alter_table('advisor_assignments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('program_id')

    # ### end Alembic commands ###
