"""Program Name not unique.

Revision ID: b2950fdaca8a
Revises: d784ee0d3bd2
Create Date: 2025-03-21 20:31:13.470279

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b2950fdaca8a'
down_revision = 'd784ee0d3bd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('advisor', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('programs', schema=None) as batch_op:
        batch_op.drop_index('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('programs', schema=None) as batch_op:
        batch_op.create_index('name', ['name'], unique=True)

    with op.batch_alter_table('advisor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', mysql.DATETIME(), nullable=True))

    # ### end Alembic commands ###
